#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 19 13:58:42 2020

@author: kissami
"""

<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="col-lg-12">
            <div class="modal-header">
                <h5 class="modal-title">Veuillez choisir une région</h5>
            </div>
            <div class="mb-3">
                <select class="form-select"> onChange="window.location.href=this.value">
                    <option selected></option>
                    <option value=Orientale>Orientale</option>   
                    <option value=Fes>Fès-Meknès</option>
                    <option value=Tanger>Tanger-Tétouan-Al Hoceïma</option>    
                    <option>  Rabat-Salé-Kénitra</option>
                    <option>  Béni Mellal-Khénifra</option>
                    <option> Casablanca-Settat</option>
                    <option>  Marrakech-Safi</option>
                    <option>  Drâa-Tafilalet</option>
                    <option>  Souss-Massa</option>
                    <option>  Guelmim-Oued Noun</option>
                    <option>  Laâyoune-Sakia El Hamra</option>
                    <option>  Dakhla-Oued Ed Dahab   </option>     
                </select>
            </div>
            <div class="modal-header">
                <h5 class="modal-title">Veuillez choisir une ville</h5>
            </div>
            <div class="mb-3">
                <select class="form-select"> onChange="window.location.href=this.value">
                    <option selected></option>
                    <option >Oujda</option>   
                    <option >Berkane</option>
                    <option >Saidia</option>    
                    <option> Ahfir</option>
                    <option> Nador</option>
               </select>
            </div>
        </div>
    </div>
</div>



  <p><a href="{% url 'logout' %}">Log Out</a></p>
  <p><a href="{% url 'password_reset' %}">Reset Password</a></p>
